# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo "Author ${{ toJson(github.event.head_commit.author) }}"
      - name: Send Teams Notification
        if: success()
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.TEAMS_WEBHOOK }}
          title: ${{ github.event.head_commit.message }} - ${{ toJson(github.event.head_commit.author.name) }}
          summary: Author ${{ toJson(github.event.head_commit.author) }}
          text: Commit Url ${{ github.event.head_commit.url }} 

      - name: Send Email Notification
        if: success()
        run: | 
          sudo apt-get install mailutils 
          echo "Commit: ${{ github.event.head_commit.url }} " | mailx -s "${{ github.event.head_commit.message }}" -aFrom:${{ secrets.EMAIL_USERNAME }} ${{ secrets.EMAIL_LIST }}


